from . import annotation, cofolding, corpus, geometry, window

# id, manuscript location, what it says, published value, tolerance, how to recompute it.
# Tolerance is absolute, on the same scale as the value. A claim needing a live query or a
# figure has no published scalar and is listed in NUMBERS.md instead.
CLAIMS = [
    ("C1", "Abstract", "flavin entries in the corpus",
     5380, 0, lambda: corpus.coverage()["entries"]),
    ("C2", "Abstract", "carry neither a title indication nor a state-specific identifier (%)",
     89.3, 0.05, lambda: corpus.coverage()["unannotated_pct"]),
    ("C3", "Results 2", "entries carrying any indication of state",
     576, 0, lambda: corpus.coverage()["annotated"]),
    ("C4", "Results 2", "annotated by identifier",
     215, 0, lambda: corpus.coverage()["by_identifier"]),
    ("C5", "Results 2", "annotated by title text",
     426, 0, lambda: corpus.coverage()["by_title"]),
    ("C6", "Results 2", "annotated by both routes",
     65, 0, lambda: corpus.coverage()["by_both"]),
    ("C7", "Results 2", "95%-identity clusters",
     1393, 0, lambda: corpus.cluster_coverage()["n_cluster95"]),
    ("C8", "Results 2", "30%-identity clusters",
     594, 0, lambda: corpus.cluster_coverage()["n_cluster30"]),
    ("C9", "Results 2", "annotated share per 95%-identity cluster (%)",
     12.2, 0.05, lambda: corpus.cluster_coverage()["cluster95"]),
    ("C10", "Results 2", "annotated share per 30%-identity cluster (%)",
     18.5, 0.05, lambda: corpus.cluster_coverage()["cluster30"]),
    ("C11", "Results 2", "30% clusters touched by the annotated entries",
     110, 0, lambda: corpus.concentration()[30]["observed"]),
    ("C12", "Results 2", "30% clusters expected at random",
     235.8, 1.5, lambda: corpus.concentration()[30]["expected"]),
    ("C13", "Results 2", "95% clusters touched by the annotated entries",
     170, 0, lambda: corpus.concentration()[95]["observed"]),
    ("C14", "Results 2", "95% clusters expected at random",
     354.2, 2.0, lambda: corpus.concentration()[95]["expected"]),
    ("C15", "Results 3", "titles reporting a reduced flavin",
     185, 0, lambda: annotation.misencoding()["titles_reporting_reduced"]),
    ("C16", "Results 3", "of those, filed under an identifier that does not encode reduction",
     124, 0, lambda: annotation.misencoding()["without_reduced_identifier"]),
    ("C17", "Results 3", "misencoded share (%)",
     67, 0.5, lambda: annotation.misencoding()["pct"]),
    ("C18", "Results 4", "Spearman rho, deposition year against annotation",
     0.015, 0.001, lambda: annotation.deposition_year_trend()["rho"]),
    ("C19", "Results 4", "its p-value",
     0.27, 0.005, lambda: annotation.deposition_year_trend()["p"]),
    ("C20", "Results 5", "unannotated share, narrowest word list (%)",
     89.59, 0.01, lambda: _wording("narrowest")),
    ("C21", "Results 5", "unannotated share, published word list (%)",
     89.29, 0.01, lambda: _wording("published")),
    ("C22", "Results 5", "unannotated share, plus dihydro (%)",
     83.70, 0.01, lambda: _wording("dihydro")),
    ("C23", "Results 5", "entries added by three further text fields",
     18, 0, lambda: annotation.extra_text_fields()["new_hits"]),
    ("C24", "Table 4", "median bend, oxidized by title (deg)",
     4.02, 0.005, lambda: _bend("oxidized", "title")),
    ("C25", "Table 4", "median bend, semiquinone (deg)",
     5.41, 0.005, lambda: _bend("semiquinone", "either")),
    ("C26", "Table 4", "median bend, reduced by identifier (deg)",
     13.50, 0.005, lambda: _bend("reduced", "identifier")),
    ("C27", "Table 4", "median bend, reduced by title (deg)",
     3.63, 0.005, lambda: _bend("reduced", "title")),
    ("C28", "Results 6", "structures measured",
     448, 0, lambda: int(geometry.deposited_bend().shape[0])),
    ("C29", "Results 6", "naive oxidized-against-reduced p-value",
     3.6e-11, 1e-12, lambda: geometry.naive_state_contrast()["p"]),
    ("C30", "Results 6", "title-labelled mean difference (deg)",
     1.14, 0.01, lambda: geometry.title_group_contrast()["mean_difference"]),
    ("C31", "Results 6", "its bootstrap lower bound (deg)",
     -0.20, 0.10, lambda: geometry.title_group_contrast()["ci_lo"]),
    ("C32", "Results 6", "its bootstrap upper bound (deg)",
     2.52, 0.10, lambda: geometry.title_group_contrast()["ci_hi"]),
    ("C33", "Results 6", "title-labelled Mann-Whitney p",
     0.66, 0.01, lambda: geometry.title_group_contrast()["p"]),
    ("C34", "Results 6", "reduced-identifier entries within 0.5 deg of the reference (%)",
     6, 0.5, lambda: geometry.restraint_check()["within_half_degree_pct"]),
    ("C35", "Results 6", "largest bend measured across the corpus (deg)",
     31.1, 0.05, lambda: geometry.restraint_check()["corpus_max"]),
    ("C36", "Results 7", "first-run targets bending further under reduced chemistry",
     32, 0, lambda: cofolding.first_run_response()["bent_further"]),
    ("C37", "Results 7", "its Wilcoxon p-value",
     7.4e-9, 1e-10, lambda: cofolding.first_run_response()["p"]),
    ("C38", "Results 7", "median predicted bend, reduced arm, first run (deg)",
     6.51, 0.01, lambda: cofolding.first_run_response()["median_reduced"]),
    ("C39", "Results 8", "targets responding in the correct direction, all 92",
     86, 0, lambda: cofolding.exposure_tests()["overall_correct"]),
    ("C40", "Table 5", "exposed families, correct direction",
     26, 0, lambda: _strat(True, "correct_direction")),
    ("C41", "Table 5", "exposed families, median shift (deg)",
     4.02, 0.01, lambda: _strat(True, "median_shift")),
    ("C42", "Table 5", "unexposed families, correct direction",
     60, 0, lambda: _strat(False, "correct_direction")),
    ("C43", "Table 5", "unexposed families, median shift (deg)",
     1.19, 0.01, lambda: _strat(False, "median_shift")),
    ("C44", "Table 5", "direction against exposure, Fisher p",
     0.18, 0.005, lambda: cofolding.exposure_tests()["direction_p"]),
    ("C45", "Table 5", "magnitude against exposure, Mann-Whitney p",
     5.5e-7, 1e-8, lambda: cofolding.exposure_tests()["magnitude_p"]),
    ("C46", "Results 8", "reduced arm as % of the reduced reference, exposed",
     86, 0.5, lambda: _strat(True, "reduced_arm_pct_of_reference")),
    ("C47", "Results 8", "the same, unexposed families (%)",
     27, 0.5, lambda: _strat(False, "reduced_arm_pct_of_reference")),
    ("C46b", "Results 8", "shift as % of the implied change, exposed families",
     29.5, 0.1, lambda: _strat(True, "shift_pct_of_implied")),
    ("C47b", "Results 8", "the same, unexposed families (%)",
     8.7, 0.1, lambda: _strat(False, "shift_pct_of_implied")),
    ("C46c", "Results 8", "median oxidized arm, exposed families (deg)",
     6.82, 0.01, lambda: _strat(True, "median_oxidized_bend")),
    ("C47c", "Results 8", "median oxidized arm, unexposed families (deg)",
     2.46, 0.01, lambda: _strat(False, "median_oxidized_bend")),
    ("C48", "Results 8", "unexposed response, sign test p",
     3e-12, 1e-12, lambda: cofolding.exposure_tests()["unexposed_sign_p"]),
    ("C49", "Results 8", "dose within exposed families, Spearman rho",
     -0.24, 0.01, lambda: cofolding.exposure_dose()["rho"]),
    ("C50", "Results 8", "its p-value",
     0.23, 0.005, lambda: cofolding.exposure_dose()["p"]),
    ("C51", "Results 7", "targets prepared for the ablation",
     312, 0, lambda: cofolding.completion_bias()["prepared"]),
    ("C52", "Results 7", "reduced-identifier entries among the 36 completed",
     24, 0, lambda: cofolding.completion_bias()["fda_completed"]),
    ("C53", "Results 7", "and among the 276 that did not complete",
     109, 0, lambda: cofolding.completion_bias()["fda_rest"]),
    ("C54", "Results 7", "median resolution of the completed set (A)",
     2.20, 0.01, lambda: cofolding.completion_bias()["resolution_completed"]),
    ("C55", "Results 7", "median resolution of the rest (A)",
     1.96, 0.01, lambda: cofolding.completion_bias()["resolution_rest"]),
    ("C56", "Results 7", "deposited bend differs between them, p",
     0.0034, 0.0005, lambda: cofolding.completion_bias()["crystal_bend_p"]),
    ("C56b", "Results 7", "median deposited bend, completed set (deg)",
     17.32, 0.01, lambda: cofolding.completion_bias()["crystal_bend_completed"]),
    ("C56c", "Results 7", "median deposited bend, the rest (deg)",
     5.45, 0.01, lambda: cofolding.completion_bias()["crystal_bend_rest"]),
    ("C34b", "Results 5", "entries carrying a state-specific identifier",
     215, 0, lambda: annotation.identifier_purity()["with_identifier"]),
    ("C34c", "Results 5", "of those, entries whose identifier and title disagree",
     4, 0, lambda: annotation.identifier_purity()["conflicts"]),
    ("C28b", "Table 4", "rows sum to fewer than the 448 measured",
     440, 0, lambda: int(geometry.bend_by_label_source().n.sum())),
    ("C57z", "Methods", "in-window title-only labels, all oxidized",
     111, 0, lambda: _confound("title only", "oxidized")),
    ("C57y", "Methods", "in-window reduced labels the identifier could have supplied",
     67, 0, lambda: _confound("identifier only", "reduced") + _confound("both", "reduced")),
    ("C50a", "Results 8", "median deposited bend, exposed families (deg)",
     21.07, 0.01, lambda: cofolding.deposited_bend_confound()["median_bend_exposed"]),
    ("C50b", "Results 8", "median deposited bend, unexposed families (deg)",
     3.97, 0.01, lambda: cofolding.deposited_bend_confound()["median_bend_unexposed"]),
    ("C50c", "Results 8", "shift against the target's deposited bend, Spearman",
     0.63, 0.01, lambda: cofolding.deposited_bend_confound()["rho_shift_vs_bend"]),
    ("C50d", "Results 8", "exposure-magnitude association, unadjusted",
     0.53, 0.01, lambda: cofolding.deposited_bend_confound()["rho_unadjusted"]),
    ("C50e", "Results 8", "the same, adjusted for deposited bend",
     0.33, 0.01, lambda: cofolding.deposited_bend_confound()["rho_adjusted"]),
    ("C50f", "Methods", "Hodges-Lehmann shift, exposed minus unexposed (deg)",
     2.72, 0.02, lambda: cofolding.location_shift()["pooled"][0]),
    ("T1r", "Abstract", "nicotinamide recorded how many times as often as flavin",
     7.2, 0.3, lambda: (lambda t: float(t.loc[t.cofactor == "nicotinamide", "pct"].iloc[0]
                                        / t.loc[t.cofactor == "flavin", "pct"].iloc[0]))(
         corpus.cofactor_classes_snapshot())),
    ("C50g", "Results 8", "upper bend stratum, median shift, exposed (deg)",
     5.47, 0.01, lambda: _strat_bend("above", "median_exposed")),
    ("C50h", "Results 8", "upper bend stratum, exposure contrast p",
     0.0001, 0.00005, lambda: _strat_bend("above", "p")),
    ("C50i", "Results 8", "lower bend stratum, exposure contrast p",
     0.13, 0.005, lambda: _strat_bend("at or below", "p")),
    ("M1", "Methods", "annotated entries excluded as time-resolved",
     57, 0, lambda: corpus.time_resolved_exclusion()["annotated_excluded"]),
    ("M2", "Methods", "that as a percentage of the annotated set",
     9.9, 0.05, lambda: corpus.time_resolved_exclusion()["annotated_pct"]),
    ("C34d", "Results 5", "identifier and title agree",
     211, 0, lambda: (annotation.identifier_purity()["with_identifier"]
                      - annotation.identifier_purity()["conflicts"])),
    ("C33a", "Results 6", "title-only entries whose title names another reducible species",
     96, 0, lambda: geometry.title_specificity()["n_ambiguous"]),
    ("C33b", "Results 6", "unambiguous-title contrast, reduced median (deg)",
     5.08, 0.01, lambda: geometry.title_specificity()["unambiguous_reduced"]),
    ("C33c", "Results 6", "unambiguous-title contrast, difference (deg)",
     0.71, 0.01, lambda: geometry.title_specificity()["unambiguous_difference"]),
    ("C63a", "Results 9", "window labels that may not be about the flavin",
     58, 0, lambda: window.title_specificity()["n_ambiguous"]),
    ("C63b", "Results 9", "unambiguous-label gap",
     0.148, 0.005, lambda: window.title_specificity()["unambiguous_gap"]),
    ("C63c", "Results 9", "its permutation p",
     0.086, 0.005, lambda: window.title_specificity()["unambiguous_p"]),
    ("C63d", "Results 9", "ambiguous out-of-window labels, AUC on their own",
     0.271, 0.005, lambda: window.ambiguous_label_split()["auc_out"]),
    ("C63e", "Results 9", "out-of-window AUC with those excluded",
     0.456, 0.005, lambda: window.title_specificity()["unambiguous_auc_out"]),
    ("C33a2", "Results 6", "reduced-only titles naming another reducible species",
     67, 0, lambda: annotation.misencoding_specificity()["n_ambiguous"]),
    ("C17b", "Results 3", "misencoded share, unambiguous titles only (%)",
     55, 0.5, lambda: annotation.misencoding_specificity()["unambiguous_pct"]),
    ("C39b", "Results 8", "families the 92 targets fall into",
     40, 0, lambda: cofolding.cluster_level_response()["n_clusters"]),
    ("C39c", "Results 8", "families responding in the correct direction",
     38, 0, lambda: cofolding.cluster_level_response()["correct_direction"]),
    ("C45b", "Results 8", "exposure contrast at family level, p",
     0.0012, 0.0002, lambda: cofolding.cluster_level_response()["exposure_p"]),
    ("C39d", "Results 8", "FAE control, median shift (deg)",
     -0.04, 0.01, lambda: cofolding.fae_control()["median_fae_shift"]),
    ("C39e", "Results 8", "FAE control, targets moving upward",
     12, 0, lambda: cofolding.fae_control()["fae_positive"]),
    ("C39f", "Results 8", "FAE shift against zero, Wilcoxon p",
     0.60, 0.01, lambda: cofolding.fae_control()["fae_vs_zero_p"]),
    ("C39g", "Results 8", "no-pocket control, median shift (deg)",
     2.11, 0.01, lambda: cofolding.no_pocket_control()["median_shift"]),
    ("C39h", "Results 8", "no-pocket control, targets bending further",
     8, 0, lambda: cofolding.no_pocket_control()["positive"]),
    ("C57", "Results 9", "unprompted predictions scored",
     271, 0, lambda: window.window_auc()["n"]),
    ("C58", "Results 9", "AUC within the training window",
     0.674, 0.001, lambda: window.window_auc()["auc_in"]),
    ("C59", "Results 9", "n within the training window",
     178, 0, lambda: window.window_auc()["n_in"]),
    ("C60", "Results 9", "AUC outside the training window",
     0.391, 0.001, lambda: window.window_auc()["auc_out"]),
    ("C61", "Results 9", "n outside the training window",
     93, 0, lambda: window.window_auc()["n_out"]),
    ("C62", "Results 9", "the in-minus-out gap",
     0.283, 0.001, lambda: window.window_gap()["gap"]),
    ("C63", "Results 9", "its permutation p-value",
     1.1e-4, 5e-5, lambda: window.window_gap()["p"]),
    ("C64", "Results 9", "out-of-window AUC against chance, p",
     0.10, 0.01, lambda: window.window_auc()["p_out"]),
    ("C65", "Results 9", "out-of-window interval, lower bound",
     0.28, 0.01, lambda: window.window_auc()["ci_out"][0]),
    ("C66", "Results 9", "out-of-window interval, upper bound",
     0.51, 0.01, lambda: window.window_auc()["ci_out"][1]),
    ("C67a", "Limitation 5", "exposed targets whose own pre-cutoff entry is FDA-coded",
     19, 0, lambda: cofolding.self_exposure()["n_self_exposed"]),
    ("C67b", "Limitation 5", "exposed targets in total",
     26, 0, lambda: cofolding.self_exposure()["n_exposed"]),
    ("C67c", "Limitation 5", "median deposited bend, self-exposed targets (deg)",
     22.85, 0.01, lambda: cofolding.self_exposure()["median_bend_self_exposed"]),
    ("C67d", "Limitation 5", "median deposited bend, the rest (deg)",
     3.96, 0.01, lambda: cofolding.self_exposure()["median_bend_not_self_exposed"]),
    ("C67e", "Limitation 5", "deposited-bend imbalance by self-exposure, p",
     2.0e-7, 5e-8, lambda: cofolding.self_exposure()["bend_balance_p"]),
    ("C67f", "Limitation 5", "self-exposure association, adjusted for deposited bend",
     0.372, 0.005, lambda: cofolding.self_exposure()["rho_adjusted"]),
    ("C67g", "Limitation 5", "its p-value",
     0.0003, 0.0001, lambda: cofolding.self_exposure()["adjusted_p"]),
    ("C68a", "Results 9", "out-of-window entries in a 95% cluster holding a pre-cutoff entry",
     73, 0, lambda: window.novelty_split()["seen95"]),
    ("C68b", "Results 9", "the same share (%)",
     78, 0.5, lambda: window.novelty_split()["pct_seen95"]),
    ("C68c", "Results 9", "out-of-window entries seen at 30% identity",
     87, 0, lambda: window.novelty_split()["seen30"]),
    ("C68d", "Results 9", "the same share (%)",
     94, 0.5, lambda: window.novelty_split()["pct_seen30"]),
    ("C68e", "Results 9", "out-of-window entries novel at 30% identity",
     6, 0, lambda: window.novelty_split()["novel30"]),
    ("C68f", "Results 9", "AUC where the protein was seen at 95% identity",
     0.336, 0.005, lambda: window.novelty_split()["auc_seen"]),
    ("C68g", "Results 9", "its p-value",
     0.03, 0.005, lambda: window.novelty_split()["p_seen"]),
    ("C68h", "Results 9", "AUC where the protein is novel at 95% identity",
     0.583, 0.005, lambda: window.novelty_split()["auc_novel"]),
    ("C68i", "Results 9", "its p-value",
     0.60, 0.01, lambda: window.novelty_split()["p_novel"]),
    ("C68j", "Results 9", "entries whose protein is novel at 95% identity",
     20, 0, lambda: window.novelty_split()["n_novel"]),
    ("C69a", "Discussion", "oxidized arm, self-exposed against the rest (fold)",
     4.28, 0.02, lambda: cofolding.multiplicative_response()["ox_arm_ratio"]),
    ("C69b", "Discussion", "reduced arm, the same fold",
     4.75, 0.02, lambda: cofolding.multiplicative_response()["red_arm_ratio"]),
    ("C69c", "Discussion", "median reduced/oxidized ratio, all 92",
     1.48, 0.01, lambda: cofolding.multiplicative_response()["median_ratio"]),
    ("C69d", "Discussion", "the ratio in exposed families",
     1.55, 0.01, lambda: cofolding.multiplicative_response()["ratio_exposed"]),
    ("C69e", "Discussion", "the ratio in unexposed families",
     1.45, 0.01, lambda: cofolding.multiplicative_response()["ratio_unexposed"]),
    ("C69f", "Discussion", "difference between those ratios, p",
     0.034, 0.005, lambda: cofolding.multiplicative_response()["ratio_exposure_p"]),
    ("C69g", "Discussion", "the response in unexposed families alone, p",
     8.4e-11, 5e-12, lambda: cofolding.multiplicative_response()["response_unexposed_p"]),
    ("C69h", "Discussion", "deposited bend against the shift in degrees, Spearman",
     0.630, 0.005, lambda: cofolding.multiplicative_response()["bend_vs_shift_rho"]),
    ("C69i", "Discussion", "deposited bend against the ratio, Spearman",
     0.129, 0.005, lambda: cofolding.multiplicative_response()["bend_vs_ratio_rho"]),
    ("C69j", "Discussion", "that correlation's p-value",
     0.22, 0.01, lambda: cofolding.multiplicative_response()["bend_vs_ratio_p"]),
]


def _strat_bend(stratum, field):
    """One cell of the bend-stratified exposure table."""
    t = cofolding.bend_stratified_exposure()
    return float(t.loc[t.stratum == stratum, field].iloc[0])

def _confound(source, state):
    """One cell of the in-window label-source table."""
    import numpy as np
    from .paths import corpus
    from .window import labelled
    d = labelled().merge(corpus()[["pdb_id", "has_code_signal", "has_title_signal"]], on="pdb_id")
    d = d[d.in_window]
    src = np.where(d.has_code_signal & ~d.has_title_signal, "identifier only",
          np.where(d.has_title_signal & ~d.has_code_signal, "title only", "both"))
    return int(((src == source) & (d.state.values == state)).sum())

def _wording(key):
    """Unannotated share for one row of the word-list sensitivity table."""
    table = annotation.wording_sensitivity()
    row = table[table.word_list.str.contains(key)]
    return float(row.unannotated_pct.iloc[0])


def _bend(state, source):
    """One cell of the deposited-bend table."""
    table = geometry.bend_by_label_source()
    row = table[(table.state == state) & (table.label_source == source)]
    return float(row.median_bend.iloc[0])


def _strat(exposed, column):
    """One cell of the exposure stratification table."""
    table = cofolding.exposure_stratification()
    return float(table[table.family_exposed == exposed][column].iloc[0])


def check_all():
    """Recompute every scalar claim and compare it against the published value."""
    results = []
    for claim_id, where, what, published, tolerance, compute in CLAIMS:
        try:
            got = float(compute())
            ok = abs(got - published) <= tolerance
            error = None
        except ImportError:
            raise                        # a missing dependency is not a failed claim
        except Exception as exc:
            got, ok, error = float("nan"), False, f"{type(exc).__name__}: {exc}"
        results.append(dict(id=claim_id, section=where, claim=what, published=published,
                            recomputed=got, agrees=ok, error=error))
    return results
